import {useEffect,useState} from 'react';
import {ArrowRight, Check, ChevronDown, Copy, Menu, MessageCircle, Play, Sparkles, Twitch, X, Youtube} from 'lucide-react';
import {server} from './config/server'; import {rules} from './data/rules'; import {faq} from './data/faq';
import hero from './assets/hero.webp'; import world from './assets/world.webp'; import book from './assets/rules-book.webp'; import sign from './assets/join-sign.webp'; import sectionBg from './assets/section-bg.webp'; import decorations from './assets/decorations.webp';

const nav=[['Главная','hero'],['О сервере','about'],['Правила','rules'],['Как попасть','join']];
function scrollTo(id:string){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
function Navbar(){const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false); useEffect(()=>{const f=()=>setScrolled(scrollY>32); addEventListener('scroll',f); f(); return()=>removeEventListener('scroll',f)},[]); return <header className={`nav ${scrolled?'nav--solid':''}`}><div className="container nav__inner"><button className="brand" onClick={()=>scrollTo('hero')} aria-label="На главную"><span className="brand__mark"><img src={hero} alt=""/></span><span><b>КОРОВА</b><small>SMP</small></span></button><nav className={`navlinks ${open?'navlinks--open':''}`}>{nav.map(([label,id])=><button key={id} onClick={()=>{scrollTo(id);setOpen(false)}}>{label}</button>)}</nav><div className="nav__status"><span className="dot"/>SERVER ONLINE <strong>{server.onlinePlayers} / {server.maxPlayers}</strong></div><button className="menu" onClick={()=>setOpen(v=>!v)} aria-label="Открыть меню">{open?<X/>:<Menu/>}</button></div></header>}
function Status(){return <div className="status-card"><div className="status-card__top"><span className="dot"/> СЕРВЕР ОНЛАЙН</div><div className="status-card__number">{server.onlinePlayers} <span>/ {server.maxPlayers}</span></div><div className="status-card__meta">Minecraft {server.serverVersion}<i/></div></div>}
function Hero(){return <section id="hero" className="hero"><div className="hero__bg" style={{backgroundImage:`url(${hero})`}}/><div className="hero__shade"/><div className="hero__grain"/><div className="container hero__content"><div className="hero__copy"><div className="eyebrow"><span>♥</span> УЮТНЫЙ MINECRAFT SMP</div><h1>МИР, КОТОРЫЙ<br/>МЫ СТРОИМ <em>ВМЕСТЕ</em></h1><p>Уютный Minecraft-сервер с друзьями, событиями и атмосферой, где хочется оставаться.</p><button className="button button--accent" onClick={()=>scrollTo('join')}>КАК ПОПАСТЬ НА СЕРВЕР <ArrowRight size={18}/></button></div><Status/></div><div className="scroll-hint"><span/> ЛИСТАЙТЕ ВНИЗ</div></section>}
const cards=[['О СЕРВЕРЕ', 'Уникальный мир, дружное сообщество, события и развитие.',world,'about'],['ПРАВИЛА','Простые и понятные правила, которые помогают сохранять комфортную атмосферу.',book,'rules'],['КАК ПОПАСТЬ','Всего несколько шагов — и ты уже внутри нашего мира.',sign,'join']];
function FeatureCards(){return <section className="cards"><div className="container cards__grid">{cards.map(([title,text,img,id],i)=><button className="card" key={title} onClick={()=>scrollTo(id)}><div className="card__art"><img src={img} alt=""/><span>0{i+1}</span></div><div className="card__body"><h3>{title}</h3><p>{text}</p><b>ПОДРОБНЕЕ <ArrowRight size={15}/></b></div></button>)}</div></section>}
function About(){return <section id="about" className="section about"><div className="container about__grid"><div className="about__visual"><div className="image-frame"><img src={world} alt="Minecraft остров с домом и водопадом"/></div><img className="deco deco--left" src={decorations} alt=""/><div className="stamp">КОРОВА<br/><small>SMP · 2026</small></div></div><div className="about__copy"><div className="eyebrow">01 / О СЕРВЕРЕ</div><h2>Здесь рождаются<br/><em>свои истории.</em></h2><p>Мы строим большой общий мир, устраиваем события, развиваем экономику и оставляем место для самых разных игровых историй.</p><ul>{['Живое сообщество','Регулярные события','Свобода строительства','Развитие мира вместе'].map(x=><li key={x}><Sparkles size={15}/>{x}</li>)}</ul><div className="stats"><div><span>ВЕРСИЯ</span><b>{server.serverVersion}</b></div><div><span>РЕЖИМ</span><b>{server.serverMode}</b></div><div><span>ИГРОКИ</span><b>{server.onlinePlayers} / {server.maxPlayers}</b></div><div><span>АДРЕС</span><b>{server.serverIp}</b></div></div></div></div></section>}
const benefits=[['УНИКАЛЬНЫЙ МИР','Живой мир, который развивается вместе с игроками.'],['СОБЫТИЯ','Регулярные ивенты и активности.'],['СООБЩЕСТВО','Сервер для людей, а не просто список игроков.'],['СВОБОДА','Строй, исследуй и создавай собственные истории.']];
function Features(){return <section className="section benefits"><div className="container"><div className="section-head"><div className="eyebrow">02 / ОСОБЕННОСТИ</div><h2>Не просто сервер.<br/><em>Общий мир.</em></h2></div><div className="benefit-grid">{benefits.map((x,i)=><article key={x[0]}><span>0{i+1}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></div></section>}
function Accordion({items}:{items:readonly (readonly [string,string])[]}){const [active,setActive]=useState<number|null>(null);return <div className="accordion">{items.map(([q,a],i)=><div className={`acc ${active===i?'acc--open':''}`} key={q}><button onClick={()=>setActive(active===i?null:i)} aria-expanded={active===i}><span><i>0{i+1}</i>{q}</span><ChevronDown size={19}/></button><div className="acc__answer"><p>{a}</p></div></div>)}</div>}
function Rules(){return <section id="rules" className="section rules"><div className="rules__bg" style={{backgroundImage:`url(${sectionBg})`}}/><div className="container rules__grid"><div className="rules__intro"><div className="eyebrow">03 / ПРАВИЛА</div><h2>Играем<br/><em>с уважением.</em></h2><p>Несколько простых принципов, чтобы общий мир оставался комфортным для всех.</p><div className="book"><img src={book} alt="Minecraft книга правил"/></div></div><Accordion items={rules.map(r=>[r.title,r.text] as const)}/></div></section>}
function Join(){const [copied,setCopied]=useState(false); const copy=async()=>{try{await navigator.clipboard.writeText(server.serverIp);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{}};return <section id="join" className="section join"><div className="container"><div className="section-head section-head--center"><div className="eyebrow">04 / КАК ПОПАСТЬ</div><h2>Твой следующий<br/><em>мир — здесь.</em></h2></div><div className="join__grid"><div className="steps">{[['ЗАПУСТИ MINECRAFT','Установи Minecraft Java Edition и нужную версию игры.'],['ОТКРОЙ СЕТЕВУЮ ИГРУ','Перейди в Multiplayer.'],['ДОБАВЬ СЕРВЕР',`Введи адрес: ${server.serverIp}`],['ЗАХОДИ И ИГРАЙ','Подключайся и присоединяйся к миру.']].map((s,i)=><article key={s[0]}><span>0{i+1}</span><div><h3>{s[0]}</h3><p>{s[1]}</p></div>{i<3&&<i/>}</article>)}</div><div className="connect"><img src={sign} alt="Деревянная табличка Minecraft"/><div className="connect__content"><div className="eyebrow">АДРЕС СЕРВЕРА</div><div className="ip">{server.serverIp}</div><div className="connect__meta"><span><small>ВЕРСИЯ</small>{server.serverVersion}</span><span><small>ПОРТ</small>{server.serverPort}</span></div><button className="button button--accent button--wide" onClick={copy}>{copied?<><Check size={18}/> IP СКОПИРОВАН ✓</>:<><Copy size={18}/> СКОПИРОВАТЬ IP</>}</button></div></div></div></div></section>}
function FAQ(){return <section className="section faq"><div className="container faq__grid"><div><div className="eyebrow">05 / FAQ</div><h2>Остались<br/><em>вопросы?</em></h2><p>Здесь собрали короткие ответы на то, что чаще всего спрашивают перед входом.</p></div><Accordion items={faq}/></div></section>}
function Footer(){return <footer><div className="container footer__top"><div className="footer__brand"><span className="brand__mark"><img src={hero} alt=""/></span><div><b>КОРОВА SMP</b><small>ВМЕСТЕ ЛУЧШЕ</small></div></div><div className="footer__links"><button onClick={()=>scrollTo('about')}>О сервере</button><button onClick={()=>scrollTo('rules')}>Правила</button><button onClick={()=>scrollTo('join')}>Как попасть</button><button onClick={()=>scrollTo('faq')}>FAQ</button></div><div className="socials"><a href={server.twitchUrl} aria-label="Twitch"><Twitch/></a><a href={server.youtubeUrl} aria-label="YouTube"><Youtube/></a><a href={server.telegramUrl} aria-label="Telegram"><SendIcon/></a><a href={server.discordUrl} aria-label="Discord"><MessageCircle/></a></div></div><div className="container footer__bottom"><span>© 2026 КОРОВА SMP</span><span>Сделано для тех, кто строит вместе.</span></div></footer>}
function SendIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" width="19" height="19"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg>}
export default function App(){useEffect(()=>{document.documentElement.style.scrollBehavior='smooth';return()=>{document.documentElement.style.scrollBehavior='auto'}},[]);return <><Navbar/><main><Hero/><FeatureCards/><About/><Features/><Rules/><Join/><div id="faq"><FAQ/></div></main><Footer/></>}
